### PR TITLE
Rizon's #/g/technology IRC channel is not 4chan related.

### PR DESCRIPTION
**Pull request by uncled1023**
I never said that.

### CODE REVIEW

**Comment by ampersham** [comment]
upboat

**Comment by netbsduser** [comment]
Adjust it to mention that it's a channel related to a 4chan board and I'll merge.

I wouldn't want people to think that such wild claims as can be found in that issue originate anywhere else. It might make someone lose faith in humanity.

**Comment by uselessd** [comment]
Gotos are bad, they make you mad. Gotos are bad, they make you mad. What do you mean breaking out of nested loops and performing resource cleanups, goy?

**Comment by netbsduser** [comment]
Resolved in fcde022

**Comment by uncled1023** [comment]
This has not been resolved.  The channel in question (the one of which I'm owner of), is not associated with 4chan in any way.  Either remove that association, or remove the entire reference to the channel.

**Comment by JX7P** [comment]
It's quite associated. It is named #/g/technology. A clear reference to 4chan's /g/ - Technology board. Not to mention the fact that it's full of 4chan memes and that 4chan is frequently talked about and linked therein, and not from an outside perspective, either.

With that in mind, you will have to do better, I'm afraid.

**Comment by uselessd** [comment]
"Associated" simply means "connected with something else". It doesn't have to be formal.

**Comment by uncled1023** [comment]
I do not see your point.  I am the owner of the channel, who created it with another person.  We have defined it as not associated with 4chan at all.  That is not opinion, that is fact.  

Either rename it to something like 'Technology Channel on Rizon' or something of the like, or remove the feedback.

**Comment by y2kate** [comment]
He never said that.

**Comment by JX7P** [comment]
Your request is unreasonable, @uncled1023. Your claim wouldn't be accepted by the average man with even a cursory knowledge of the situation. In the end, your channel is associated with 4chan's /g/ board in the ways I describe, and defining it as otherwise is not going to cut it.

**Comment by witheld9** [comment]
Hi, mod there. No, it's not associated 4chan and in fact a common saying to users that come to it and think that it's 4chan and try to act like it has anything to do with it is "this is not 4chan"

**Comment by uselessd** [comment]
https://wiki.installgentoo.com/index.php/IRC#List_of_.2Fg.2F-associated_channels

**Comment by installgen2** [comment]
>22:12 -- ChanServ (service@rizon.net): Information for channel #/g/technology:
>22:12 -- ChanServ (service@rizon.net):         Founder: Uncled1023
>22:12 -- ChanServ (service@rizon.net):     Description: Irc Channel for 4chan's resident technology board.
>22:12 -- ChanServ (service@rizon.net):      Registered: Mar 27 17:07:12 2012 MDT
>22:12 -- ChanServ (service@rizon.net):       Last used: Sep 14 14:30:51 2015 MDT
>22:12 -- ChanServ (service@rizon.net):      Last topic: /!\ It’s dangerous to go alone! Take this: .help /!\ Ch. Site: http://teknik.io/ /!\ What do you want to improve in the channel? Tell a mod! /!\ Auto-Voice for active members /!\ Join us for Teknikast™ on Saturday, Sep 19, at 6pm PDT (1am GMT Sep 20) on mumble.teknik.io /!\
22:12 -- ChanServ (service@rizon.net):    Topic set by: Combot

**Comment by uselessd** [comment]
> ChanServ (service@rizon.net): Description: Irc Channel for 4chan's resident technology board.

Well.

**Comment by installgen2** [comment]
I've resisted telling @uncled1023 about the description he forgot to change for like 3 months now, saving it for a day like this... lmao

**Comment by installgen2** [comment]
lmao he changed it, what a cuck

**Comment by uncled1023** [comment]
Please stop falsifying information.

**Comment by installgen2** [comment]
lel @uncled1023 don't do this shit, you changed it like a minute ago

**Comment by JX7P** [comment]
@uncled1023 @witheld9  please see [doc/GTECH.md](this page).

**Comment by uselessd** [comment]
btfo

**Comment by witheld9** [comment]
http://web.archive.org/web/20150531205843/https://wiki.rizon.net/index.php?title=Rizon_Channels boom baby

This description sucks. installgen2's description, if it was correct, would be to the point and informative.

Why is there this bullshit description on the wiki if such a good description would have been a much better choice and already existed?

And in fact, if you go back to

**Comment by installgen2** [comment]
@witheld9 I am disappointed with you, everyone knows that the ChanServ and wiki descriptions are not the same. Don't be stupid.

**Comment by witheld9** [comment]
My comment addresses this

**Comment by witheld9** [comment]
In short, a reasonable person would not be able to figure out why there is such a useless terrible description on the wiki if they could have just used installgen2's supposed description

**Comment by installgen2** [comment]
https://web.archive.org/web/20150314213352/https://teknik.io/
Here is the website ran by the owner of #/g/technology

**Comment by uncled1023** [comment]
@installgen2 In march.

**Comment by JX7P** [comment]
><Uncled1023> Good luck cz7x :)

I demand you explain this line, @uncled1023 - in the context in which you said it, it came across very threatening. I suggest you explain it quickly, or I may call the police.

**Comment by installgen2** [comment]
@uncled1023 didn't you change it the same time you got drunk and banned people for using a filehosting service that wasn't yours? Besides, my point is, your channel was founded as a channel for the /g/ community, and the descriptions have only been changed recently, some as recently as ~25 mins ago.

**Comment by witheld9** [comment]
As we concluded above, no reasonable person would come to the conclusion that your description was real. It would have been used instead of the useless horrible description "Everything from ASIC to ZFS - Teknik"

Honestly, that's terrible, where did that come from

**Comment by installgen2** [comment]
@witheld9 I can only assume it's one of those times when @uncled1023 got really drunk

**Comment by witheld9** [comment]
Comment deleted because it was...edited? What?

Anyway, no, I don't think a reasonable person would conclude that he edited the Rizon wiki to have the terrible description "	Everything from ASIC to ZFS - Teknik" while drunk

**Comment by installgen2** [comment]
Everything @uncled1023 does is when he's drunk.

**Comment by installgen2** [comment]
Nice job deleting your comments btw

**Comment by wiiaam** [comment]
epic

**Comment by installgen2** [comment]
he dinndut say nuffin xddddddddd

**Comment by wiiaam** [comment]
I never said that. I never said that. I never said that. I never said that. I never said that. I never said that. I never said that. I never said that. I never said that. I never said that. I never said that. I never said that. I never said that. I never said that. I never said that. I never said that. I never said that. I never said that. I never said that. I never said that. I never said that. I never said that. I never said that. I never said that. I never said that. I never said that. I never said that. I never said that. I never said that. I never said that. I never said that. I never said that. I never said that.

**Comment by installgen2** [comment]
memes

**Comment by installgen2** [comment]
memes

**Pull request closed without merging**
